### ISSUE TITLE
Unclear licensing terms

### ISSUE THREAD

**Issue by lgbaldoni** [MatthiasSchinzel/sysmon#9]
Perhaps it's still preliminary, but as things stand now it would be impossible to package and distribute this application.

**Comment by MatthiasSchinzel** [comment]
I know I am also not happy about the current situation. To be honest I am not an expert with this licensing stuff.

Me personally, I don't have any problem releasing this tool under the MIT license. I am however not sure if I can, because there are dependencies to pyqt5 (GNU GPL) and pyqtgraph (MIT open-source). So I also want to respect their work and want to make sure there is no problem with their pyqt5 license. 

As I said, I am really not an expert on this topic. I will do some research about this topic, or maybe you also know that kind of stuff?

**Comment by lgbaldoni** [comment]
> Me personally, I don't have any problem releasing this tool under the MIT license. I am however not sure if I can, because there are dependencies to pyqt5 (GNU GPL) and pyqtgraph (MIT open-source). So I also want to respect their work and want to make sure there is no problem with their pyqt5 license.

If it's not a derivative work, the licensing terms of other python modules loaded at runtime should not have any bearing on it.

**Comment by MatthiasSchinzel** [comment]
Not sure though. To be on the safe side I will use GPLv3

https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

**Comment by lgbaldoni** [comment]
So, just to be sure, you mean GPL 3.0 only, not GPL 3.0 or any later version.
